require('guido.set')
require('guido.colorscheme')
require('guido.keymaps')
require('guido.autopair')
require('guido.plugins')
require('guido.lualine')
require('guido.remap')
require('guido.treesitter')
require('guido.cmp')
require('guido.telescope')
require('guido.bufferline')
require('guido.lspsaga')
require('guido.mason')
require('guido.lspkind')
require('guido.prettier')
require('guido.colorizer')
require('guido.comment')
require('guido.nvimtree')
require('guido.toggleterm')
require('guido.autotag')
require('guido.autotag')
require('guido.git')
require('guido.gitsigns')

--require('guido.compe')  -- trying to see if it changes something
