require('guido.set')
require('guido.keymaps')
require('guido.plugins')
require('guido.telescope')
require('guido.treesitter')
-- require('guido.undotree')
require('guido.fugitive')
require('guido.lsp')
-- require('guido.vimtex')
-- require('guido.quarto')
-- require('guido.jupynium') -- dont need to call it to work
require('guido.harpoon')
